import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[shell]
program = "/opt/homebrew/bin/zsh"

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[window]
decorations = "Buttonless"
padding = { x = 2, y = 2}
option_as_alt = "Both"
startup_mode = "Maximized"

[font]
size = 12.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[keyboard]
bindings = [
{ key = "Right", mods = "Alt",       chars = "\u001BF" },
{ key = "Left",  mods = "Alt",       chars = "\u001BB" },
{ key = "E",     mods = "Alt",       chars = "é"       },
{ key = "E",     mods = "Alt|Shift", chars = "è"       },
{ key = "A",     mods = "Alt",       chars = "à"       },
]
