eval "$(/opt/homebrew/bin/brew shellenv)"

source <(fzf --zsh)
eval "$(zoxide init --cmd j zsh)"
eval "$(starship init zsh)"

alias reload!='source ~/.zshrc'

alias e='nvim'
alias vi='nvim'
alias vim='nvim'
export EDITOR='e'

alias ls='eza -lh --group-directories-first --icons --hyperlink'
alias lsa='ls -a'
alias lt='eza --tree --level=2 --long --icons --git'
alias lta='lt -a'

